In [6]:
import torch
import numpy as np

In [3]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x = torch.tensor([3,5,6], dtype=torch.float)
counts = np.array([0, 0, 0], dtype='float')
for _ in range(1000):
    arg = torch.multinomial(x, 1)
    counts[arg] += 1

In [72]:
counts /= 1000
counts

array([0.218, 0.358, 0.424])

In [76]:
x / x.sum()

tensor([0.2143, 0.3571, 0.4286])

In [87]:
torch.multinomial(x, 1).item()

1